name: copy schema.graphqls from graphql-back
on:
  repository_dispatch:
    types: [target-updated]
jobs:
  copy-target:
    name: copy target.yml
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone repository1
        uses: actions/checkout@v2
        with:
          repository: asSqr/graphql-back
          path: graphql-back
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: copy schema.graphqls
        run: cp graphql-back/graph/schema.graphqls schema.graphqls
      - name: clean graphql-back
        run: rm -rf graphql-back
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: 'copy schema.graphqls'
          branch: copy_schema
          branch-suffix: timestamp
          delete-branch: true
          title: 'updated schema.graphqls'